### ISSUE TITLE
Binding in 1.4.1

### ISSUE THREAD

**Issue by Savvkin** [NancyFx/Nancy.Serialization.ServiceStack#16]
Hello.

Bind<T> works fine with native serialization, but with Nancy.Serialization.ServiceStack 1.4.1 + ServiceStack.Text 3.9.71 is doesn't work when called two times in a row. Second instance is not deserialized.
![Binding problem](https://dl.dropboxusercontent.com/u/17131034/Binding.png)

It also will be nice if Nancy.Serialization.ServiceStack use latest NuGet of 3x ServiceStack.Text 3.9.71 instead of outdated 3.9.11.

**Comment by khellang** [comment]
> It also will be nice if Nancy.Serialization.ServiceStack use latest NuGet of 3x ServiceStack.Text 3.9.71 instead of outdated 3.9.11.

Can't you update that dependency yourself? We only specify the minimum version, so unless there are breaking changes (in a patch release, ugh :disappointed:), it should work fine with a newer version :smile:
